public:
  #######################################通常项目实施上需要修改的配置型########
  #nginx的ip地址，平台类的肯定填的是nginx地址，三方跟决策流如果集群也是用的nginx地址，如使用单点的，请自行修改下面的配置
  nginx-host: http://10.100.1.63
  #数据库url目前默认是统一的
  db-url: jdbc:oracle:thin:@//10.100.1.85:1521/orcl
  #平台名称
  platform-name: 智能反欺诈平台
  #assets连接
  assets-jdbcUrl: ${public.db-url}
  assets-username: SDM_7170
  assets-password: bangsun
  #trans连接
  trans-flow-jdbcUrl: ${public.db-url}
  trans-flow-username: bsfit_mgr
  trans-flow-password: bangsun
  #risk连接
  risk-jdbcUrl: ${public.db-url}
  risk-username: bsfit_mgr
  risk-password: bangsun
  #持久化连接
  indicator-jdbcUrl: ${public.db-url}
  indicator-username: bsfit_mgr
  indicator-password: bangsun
  #规则回测连接
  dom-jdbcUrl: ${public.db-url}
  dom-username: bsfit_sdm
  dom-password: bangsun
  #as地址
  aerospike: 10.100.2.60:3000
  #redis地址
  redis: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382
  #kafka地址
  kafka: 10.100.2.60:9392,10.100.2.60:9392,10.100.2.60:9392
  #zk地址
  zookeeper: 10.100.2.70:2181,10.100.2.60:2181,10.100.2.80:2181
  #决策平台地址context-path不需要配默认/ss
  smart-decision-mgr: ${public.nginx-host}:7170
  #流立方服务端地址（集群情况下填任意一个服务端）
  stream-cube-server: http://10.100.2.60:8555
  #决策引擎地址
  smart-decision-engine: http://10.100.1.100:9180
  workflow-engine:
    #决策流引擎生产地址
    prods: 10.100.1.132:9093
    #决策流引擎仿真地址
    simulations: ${public.nginx-host}:9093
  #三方地址
  third-party-module: ${public.nginx-host}:9191
  #名单地址
  namelist: ${public.nginx-host}:7170
  #PA地址
  pipeace: ${public.nginx-host}:7170
  #前置机
  front.server.url: http://10.100.1.161:10888
  ####################################################################################
  ##重复的配置
  #数据库类型
  dbType: oracle
  #driverClassName
  driverClassName: oracle.jdbc.OracleDriver

#############################1、bsfit-portal相关配置#############################
portal:
  primary:
    platform-name: ${public.platform-name}
    platform-english-name: Real-Time Intelligent Platform
  security:
    login-url: /login2.html
  index-page:
    url: /ss/main.html
  switch-control:
    # 主题颜色
    theme-color: '#377cff'
      # 登录页面主题颜色
    login-theme-color: '#0D2DB5'
    # 退出后是否重定向
    log-out-redirect: false
# pagehelper配置
pagehelper:
  helper-dialect: ${public.dbType}
##############################2、第三方中间件相关配置##############################
# 1)数据库
# 资产类数据库(dd、function、jar、指标、规则、作业……)
assets.jdbc:
  type: ${public.dbType}
  driverClassName: ${public.driverClassName}
  jdbcUrl: ${public.assets-jdbcUrl}
  username: ${public.assets-username}
  password: ${public.assets-password}
  maximumPoolSize: 40
  minimumIdle: 1
  maxLifetime: 2000000
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1 from dual
  autoCommit: false
# 流水数据库
trans-flow.jdbc:
  type: ${public.dbType}
  driverClassName: ${public.driverClassName}
  jdbcUrl: ${public.trans-flow-jdbcUrl}
  username: ${public.trans-flow-username}
  password: ${public.trans-flow-password}
  maximumPoolSize: 20
  minimumIdle: 1
  maxLifetime: 2000000
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1 from dual
  autoCommit: false
# 风险数据库
risk.jdbc:
  type: ${public.dbType}
  driverClassName: ${public.driverClassName}
  jdbcUrl: ${public.risk-jdbcUrl}
  username: ${public.risk-username}
  password: ${public.risk-password}
  maximumPoolSize: 20
  minimumIdle: 1
  maxLifetime: 2000000
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1 from dual
  autoCommit: false
# 指标数据持久化库
indicator.jdbc:
  type: ${public.dbType}
  driverClassName: ${public.driverClassName}
  jdbcUrl: ${public.indicator-jdbcUrl}
  username: ${public.indicator-username}
  password: ${public.indicator-password}
  maximumPoolSize: 20
  minimumIdle: 1
  maxLifetime: 2000000
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1 from dual
  autoCommit: false
dom.jdbc:
  type: ${public.dbType}
  driverClassName: ${public.driverClassName}
  jdbcUrl: ${public.dom-jdbcUrl}
  username: ${public.dom-username}
  password: ${public.dom-password}
  maximumPoolSize: 20
  minimumIdle: 1
  maxLifetime: 2000000
  connectionTimeout: 30000
  idleTimeout: 30000
  connectionTestQuery: SELECT 1
  autoCommit: false
# 2)缓存
cache:
  # AEROSPIKE or REDIS
  type: AEROSPIKE
  redis:
    nodes: ${public.redis}
    connection-timeout: 2000
    #password: bangsun # redis集群密码
  aerospike:
    nodes: ${public.aerospike}
# 3)kafka
kafka:
  brokers: ${public.kafka}
  compression-type: gzip
  producer:
    # kafka最大请求字节数，单位字节
    max-request-size: 33554432
    max-block-ms: 6000
    retries: 0
    # 需要server接收到数据之后发出的确认接收的信号，此项配置就是指procuder需要多少个这样的确认信号
    acks: all
    # 默认的批量处理消息字节数，单位字节
    batch-size: 16384
    # 消息压缩方式
    compression-type: gzip
    # 强制元数据时间间隔
    metadata-max-age: 120000
  consumer:
    group-id: frms
    offset-reset: earliest
    enable-auto-commit: true
    auto-commit-interval-ms: 1000
    session-timeout-ms: 15000
    # 消费者能读取的最大消息,单位字节
    fetch-max-bytes: 52428800
    fetch-max-wait-ms: 6000
    # listener并发数量
    listener-concurrency: 3
    # poll timeout
    listener-poll-timeout-ms: 1000
# 4)zookeeper
zookeeper:
  connect-string: ${public.zookeeper}
  session-timeout-ms: 10000
  connect-timeout-ms: 10000
  # zk节点最大的size
  maxbuffer: 1048575
  # Max number of times to retry
  max-retries: 10
  # Initial amount of time to wait between retries
  base-sleeptime-ms: 50
  # Max time in ms to sleep on each retry
  max-sleep-ms: 500
#################################3、各组件url配置#################################
# 1)智能决策平台地址
smart-decision-mgr:
  url: ${public.smart-decision-mgr}
  context-path: /ss/sdm/
  username: restUser
  password: 8ang$un
# 2)流立方地址
stream-cube-server:
  url: ${public.stream-cube-server}
  # 流立方多集群配置
#  cluster.schemas:
#    - name: schema1
#      url: http://10.100.1.100:8550
#    - name: schema2
#      url: http://10.100.1.101:8550
# 3)决策引擎地址
smart-decision-engine:
  url: ${public.smart-decision-engine}
# 4)决策流地址
workflow-engine:
  prods:
    - url: ${public.workflow-engine.prods}
      name: 生产环境
  simulations:
    - url: ${public.workflow-engine.simulations}
      name: 仿真环境
# 5)三方数据采集组件地址
third-party-module:
  url: ${public.third-party-module}
# 6)名单平台地址
namelist:
  url: ${public.namelist}
  context-path: /ss/nl/
  username: restUser
  password: 8ang$un
# 7)pipeace管理平台地址
pipeace:
  url: ${public.pipeace}
  context-path: /ss/pipe/
  username: restUser
  password: 8ang$un
# 8)前置机地址
front:
  server.url: ${public.front.server.url}
# 9)云服务地址
cloud:
  service:
    url: http://10.100.1.161:10060
    app-key: xId1jPdJG6Yifnm4VgSb
    app-secret: xxxx
# 10)license配置
license:
  # license server地址
  server:
    url: http://10.100.1.63:5080/authorize
  # 云端受限license的验证url
  cloud:
    url: http://cloud.bsfit.com.cn
application-public-version: 1.0.2